version: '3'

services: 
  app: 
    build: .
    command: npm start
    ports: 
      - '8080:8080'
    volumes: 
      - .:/usr/app

  db:
    container_name: 'database'
    image: mysql:5.7.31
    command: --default-authentication-plugin=mysql_native_password --sql_mode=NO_ENGINE_SUBSTITUTION,NO_AUTO_CREATE_USER --explicit_defaults_for_timestamp
    restart: always
    ports: 
      - '3309:3306'
    environment: 
      - MYSQL_ROOT_PASSWORD=root
      - TZ=Brasilia/DF